name: Docker Image CI

on:
  push:
    branches: [ "branchtest-1" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
    - run: docker build -t quelpoke .

Auth:
     - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.KEY }}

RUN:
  run docker tag quelpoke europe-west9-docker.pkg.dev/infal-devops-sysops/student-alexandre-quelpoke:latest
  run docker push europe-west9-docker.pkg.dev/infal-devops-sysops/student-alexandre/quelpoke
