name: Docker Image CI

on:
  push:
    branches: [ "branchtest-1" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
    - run: docker build -t quelpoke .

